### ISSUE TITLE
Train error reporting problems with your training set

### ISSUE THREAD

**Issue by partcompany** [fpv-iplab/DA-RetinaNet#6]
When I use the data set you annotated for training, there is an error, do you know how to solve this problem? 
 `[07/08 12:48:08 d2.data.build]: Using training sampler TrainingSampler
[07/08 12:48:08 d2.data.common]: Serializing 1502 elements to byte tensors and concatenating them all ...
[07/08 12:48:08 d2.data.common]: Serialized dataset takes 0.46 MiB
[07/08 12:48:08 detectron2]: Starting training from iteration 0
Traceback (most recent call last):
  File "/media/crazy/3A7C6F107C6EC66B/pycharmcode/detectron2/detectron2/demo/uda_train.py", line 171, in <module>
    do_train(cfg_source,cfg_target,model)
  File "/media/crazy/3A7C6F107C6EC66B/pycharmcode/detectron2/detectron2/demo/uda_train.py", line 120, in do_train
    loss_dict = model(data_source, False, alpha3, alpha4, alpha5)
  File "/home/crazy/anaconda3/envs/detectron2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() takes 2 positional arguments but 6 were given`

**Comment by GiovanniPasq** [comment]
Hello,
can you give me more details? Did you replace the retinanet.py file with our retinanet.py? Did you install the exact version of detectron2 (0.2.1)?

**Comment by partcompany** [comment]
Thanks reply，
I replaced the two files fpn.py and retinanet.py according to your instructions, run the script uda_train.py for COCO annotations.
The environment is pytorch1.8 and detectron2（0.6）and cuda10.1

**Comment by GiovanniPasq** [comment]
the problem is related to the version of detectron2, if you can use the right version (0.2.1) it should works. Could you try to start your experiments using the google colab notebook or build the container starting from the docker file that we provided?
Unfortunately with the newer version of detectron2 the authors changed drastically the implementation of retinanet. I will try to update this code matching the 0.6 but i am not sure i could do it so easily

**Comment by partcompany** [comment]
ok, I'll experiment with your suggestion, thanks!

**Comment by GiovanniPasq** [comment]
if you still have some problems, please let me know. I will try to help you asap :)

**Comment by GiovanniPasq** [comment]
Hello,
I wrote a version of DA-RetinaNet that is able to work with detectron2 0.6. However this version is not tested as well as the 0.2.1. Please follow the following step (i will assume that you have the original version of fpn.py and dense_detector.py belonging to detectron2 0.6):
1) in the fpn.py (inside the forward method), replace the line 167:
    ```return {f: res for f, res in zip(self._out_features, results)}``` ->  ```return {f: res for f, res in zip(self._out_features, results)}, bottom_up_features```
2) retinanet.py script must remain as it is by default (as it is in the detectron2 0.6)
3) move the GradReverse, DiscriminatorRes3, DiscriminatorRes4, DiscriminatorRes5  module to dense_detector.py
4) import inside the dense_detector.py  ```from fvcore.nn import sigmoid_focal_loss_jit```
5) inside dense_detector.py, below the line ```self.backbone = backbone``` add the following lines: 
 ``` 
self.discriminatorRes3 = DiscriminatorRes3()
self.discriminatorRes4 = DiscriminatorRes4()
self.discriminatorRes5 = DiscriminatorRes5()
```
6) replace the forward method of dense_detector.py with the following one:
```
def forward(self, batched_inputs: List[Dict[str, Tensor]], domain_target = False, alpha3 = 1, alpha4 = 1, alpha5 = 1):
        """
        Args:
            batched_inputs: a list, batched outputs of :class:`DatasetMapper` .
                Each item in the list contains the inputs for one image.
                For now, each item in the list is a dict that contains:
                * image: Tensor, image in (C, H, W) format.
                * instances: Instances
                Other information that's included in the original dicts, such as:
                * "height", "width" (int): the output resolution of the model, used in inference.
                  See :meth:`postprocess` for details.
        Returns:
            In training, dict[str, Tensor]: mapping from a named loss to a tensor storing the
            loss. Used during training only. In inference, the standard output format, described
            in :doc:`/tutorials/models`.
        """
        images = self.preprocess_image(batched_inputs)
        features, res = self.backbone(images.tensor)
        if self.training:
            loss_res3 = self.discriminatorRes3(res["res3"], domain_target, alpha3)
            loss_res4 = self.discriminatorRes4(res["res4"], domain_target, alpha4)
            loss_res5 = self.discriminatorRes5(res["res5"], domain_target, alpha5)
            if domain_target:
                return {"loss_r3": loss_res3, "loss_r4": loss_res4, "loss_r5": loss_res5}
            else:
                loss_discriminators = {"loss_r3": loss_res3, "loss_r4": loss_res4, "loss_r5": loss_res5}

        features = [features[f] for f in self.head_in_features]
        predictions = self.head(features)

        if self.training:
            assert not torch.jit.is_scripting(), "Not supported"
            assert "instances" in batched_inputs[0], "Instance annotations are missing in training!"
            gt_instances = [x["instances"].to(self.device) for x in batched_inputs]
            losses = self.forward_training(images, features, predictions, gt_instances)
            losses.update(loss_discriminators)
            return losses
        else:
            results = self.forward_inference(images, features, predictions)
            if torch.jit.is_scripting():
                return results

            processed_results = []
            for results_per_image, input_per_image, image_size in zip(
                results, batched_inputs, images.image_sizes
            ):
                height = input_per_image.get("height", image_size[0])
                width = input_per_image.get("width", image_size[1])
                r = detector_postprocess(results_per_image, height, width)
                processed_results.append({"instances": r})
            return processed_results
```
7) replace the do_train function with the following one:
```
def do_train(cfg_source, cfg_target, model, resume = False):
    
    model.train()
    optimizer = build_optimizer(cfg_source, model)
    scheduler = build_lr_scheduler(cfg_source, optimizer)
    checkpointer = DetectionCheckpointer(model, cfg_source.OUTPUT_DIR, optimizer=optimizer, scheduler=scheduler)

    start_iter = (checkpointer.resume_or_load(cfg_source.MODEL.WEIGHTS, resume=resume).get("iteration", -1) + 1)
    max_iter = cfg_source.SOLVER.MAX_ITER

    periodic_checkpointer = PeriodicCheckpointer(checkpointer, cfg_source.SOLVER.CHECKPOINT_PERIOD, max_iter=max_iter)
    writers = default_writers(cfg_source.OUTPUT_DIR, max_iter) if comm.is_main_process() else []

    i = 1
    max_epoch = 41.27 # max iter / min(data_len(data_source, data_target))
    current_epoch = 0
    data_len = 1502

    alpha3 = 0
    alpha4 = 0
    alpha5 = 0

    data_loader_source = build_detection_train_loader(cfg_source)
    data_loader_target = build_detection_train_loader(cfg_target) 
    logger.info("Starting training from iteration {}".format(start_iter))

    with EventStorage(start_iter) as storage:
        for data_source,data_target, iteration in zip(data_loader_source, data_loader_target, range(start_iter, max_iter)):
            storage.iter = iteration

            iteration = iteration + 1
            if (iteration % data_len) == 0:
                current_epoch += 1
                i = 1

            p = float( i + current_epoch * data_len) / max_epoch / data_len
            alpha = 2. / ( 1. + np.exp( -10 * p)) - 1
            i += 1

            alpha3 = alpha
            alpha4 = alpha
            alpha5 = alpha

            if alpha3 > 0.5:
                alpha3 = 0.5

            if alpha4 > 0.5:
                alpha4 = 0.5

            if alpha5 > 0.1:
                alpha5 = 0.1

            loss_dict = model(data_source, False, alpha3, alpha4, alpha5)
            loss_dict_target = model(data_target, True, alpha3, alpha4, alpha5)
            loss_dict["loss_r3"] += loss_dict_target["loss_r3"]
            loss_dict["loss_r4"] += loss_dict_target["loss_r4"]
            loss_dict["loss_r5"] += loss_dict_target["loss_r5"]

            loss_dict["loss_r3"] *= 0.5
            loss_dict["loss_r4"] *= 0.5
            loss_dict["loss_r5"] *= 0.5
            losses = sum(loss_dict.values())
            assert torch.isfinite(losses).all(), loss_dict

            loss_dict_reduced = {k: v.item() for k, v in comm.reduce_dict(loss_dict).items()}
            losses_reduced = sum(loss for loss in loss_dict_reduced.values())
            if comm.is_main_process():
                storage.put_scalars(total_loss=losses_reduced, **loss_dict_reduced)

            optimizer.zero_grad()
            losses.backward()
            optimizer.step()
            storage.put_scalar("lr", optimizer.param_groups[0]["lr"], smoothing_hint=False)
            scheduler.step()

            if iteration - start_iter > 5 and ((iteration + 1) % 20 == 0 or iteration == max_iter - 1):
                for writer in writers:
                    writer.write()
            periodic_checkpointer.step(iteration)
```
 I hope this could help you to fix the problem. Let me know :)
