### ISSUE TITLE
What GPU do you use to train the network, please

### ISSUE THREAD

**Issue by Shichang-Fu** [fpv-iplab/DA-RetinaNet#7]
Hello author, thank you for your outstanding work. I'm having some problems trying to use your code, and I'm using your network on my own dataset. I used your default configuration, but having problems with CUDA out of memory on 3090 (24G), I turned down batch and adjusted resnet101 to resnet50. But I still have this problem. In addition, I run the code on A800 (80G), the configuration is as follows, under this configuration, I successfully run, but the  memory occupies nearly 80G, I do not know whether this situation is normal. What GPU are you using and what's wrong with my recurring presence?Thanks！
![image](https://github.com/fpv-iplab/DA-RetinaNet/assets/103252169/11028402-abf2-4a89-b876-05dbb885f5b3)
![image](https://github.com/fpv-iplab/DA-RetinaNet/assets/103252169/59ce6aa0-47ec-4cd3-9929-7c2850974f87)

**Comment by Shichang-Fu** [comment]
Even on the A800 this configuration still reports an error:CUDA out of memory

**Comment by GiovanniPasq** [comment]
Hello,
the problem should be related to the batch size. In particular from what i see in your code, you need to set the dimension of the batch in the cfg_target object. By default, this parameter is set to 16, so in total you have a batch size of 18 and for this reason request all this GPU memory. In my experiments i used a K80 which have less memory of yours. Please try to add the following instruction to your code:
```
cfg_target.SOLVER.IMS_PER_BATCH = 2
```
Let me know is this solve your problem.
Kind Regards,
Giovanni

**Comment by Shichang-Fu** [comment]
Thank you very much for your reply. Yes, as you said, my configuration has this problem.I have found this problem and added cfg_target.SOLVER.IMS_PER_BATCH = 2 as you said. However, I found that there are still strange phenomena in the execution process
![image](https://github.com/fpv-iplab/DA-RetinaNet/assets/103252169/f75026dc-3ea3-496a-8011-5be87645a7a9)
But there are still errors on the A800! I'm confused. I used your code, just registered my own data set, changed the values of max_iter and data_len, and left the rest of the code unchanged.

The training log is as follows, and I see that the memory keeps increasing.I don't know what's wrong with me

`[11/17 01:18:50 d2.utils.events]:  iter: 18  total_loss: 2.855  loss_cls: 1.732  loss_box_reg: 0.812  loss_r3: 0.08665  loss_r4: 0.08379  loss_r5: 0.1808     lr: 3.7964e-06  max_mem: 22645M
[11/17 01:19:07 d2.utils.events]:  eta: 16:59:41  iter: 38  total_loss: 1.915  loss_cls: 1.102  loss_box_reg: 0.4451  loss_r3: 0.08663  loss_r4: 0.08424  loss_r5: 0.1648     lr: 7.7924e-06  max_mem: 22645M
[11/17 01:19:25 d2.utils.events]:  eta: 17:16:10  iter: 58  total_loss: 1.944  loss_cls: 1.138  loss_box_reg: 0.4512  loss_r3: 0.08663  loss_r4: 0.08332  loss_r5: 0.1698     lr: 1.1788e-05  max_mem: 22645M
[11/17 01:19:44 d2.utils.events]:  eta: 18:04:00  iter: 78  total_loss: 2.037  loss_cls: 1.192  loss_box_reg: 0.4952  loss_r3: 0.08664  loss_r4: 0.08296  loss_r5: 0.1674     lr: 1.5784e-05  max_mem: 22645M
[11/17 01:20:04 d2.utils.events]:  eta: 19:56:12  iter: 98  total_loss: 1.756  loss_cls: 1.012  loss_box_reg: 0.3872  loss_r3: 0.08655  loss_r4: 0.08346  loss_r5: 0.1777     lr: 1.978e-05  max_mem: 49816M
[11/17 01:20:21 d2.utils.events]:  eta: 16:48:21  iter: 118  total_loss: 1.855  loss_cls: 1.127  loss_box_reg: 0.4098  loss_r3: 0.08659  loss_r4: 0.0833  loss_r5: 0.1499     lr: 2.3776e-05  max_mem: 49816M
[11/17 01:20:39 d2.utils.events]:  eta: 17:09:24  iter: 138  total_loss: 1.798  loss_cls: 1.001  loss_box_reg: 0.4166  loss_r3: 0.08658  loss_r4: 0.08339  loss_r5: 0.1568     lr: 2.7772e-05  max_mem: 49816M
[11/17 01:20:56 d2.utils.events]:  eta: 17:13:31  iter: 158  total_loss: 1.756  loss_cls: 1.019  loss_box_reg: 0.4283  loss_r3: 0.08652  loss_r4: 0.08139  loss_r5: 0.1334     lr: 3.1768e-05  max_mem: 49816M
[11/17 01:21:14 d2.utils.events]:  eta: 17:28:17  iter: 178  total_loss: 1.471  loss_cls: 0.8268  loss_box_reg: 0.3573  loss_r3: 0.08647  loss_r4: 0.0821  loss_r5: 0.1578     lr: 3.5764e-05  max_mem: 49816M
[11/17 01:21:35 d2.utils.events]:  eta: 20:06:22  iter: 198  total_loss: 1.438  loss_cls: 0.7789  loss_box_reg: 0.3587  loss_r3: 0.08645  loss_r4: 0.08058  loss_r5: 0.1461     lr: 3.976e-05  max_mem: 54479M
[11/17 01:21:52 d2.utils.events]:  eta: 16:53:48  iter: 218  total_loss: 1.33  loss_cls: 0.642  loss_box_reg: 0.3562  loss_r3: 0.08641  loss_r4: 0.07963  loss_r5: 0.1417     lr: 4.3756e-05  max_mem: 54479M
[11/17 01:22:10 d2.utils.events]:  eta: 17:42:04  iter: 238  total_loss: 1.267  loss_cls: 0.5687  loss_box_reg: 0.3891  loss_r3: 0.08636  loss_r4: 0.07983  loss_r5: 0.1204     lr: 4.7752e-05  max_mem: 54479M
[11/17 01:22:28 d2.utils.events]:  eta: 17:26:54  iter: 258  total_loss: 1.053  loss_cls: 0.4411  loss_box_reg: 0.3376  loss_r3: 0.08631  loss_r4: 0.07978  loss_r5: 0.1262     lr: 5.1748e-05  max_mem: 54479M
[11/17 01:22:46 d2.utils.events]:  eta: 17:04:56  iter: 278  total_loss: 0.9665  loss_cls: 0.3884  loss_box_reg: 0.308  loss_r3: 0.08623  loss_r4: 0.07853  loss_r5: 0.1238     lr: 5.5744e-05  max_mem: 54479M
[11/17 01:23:04 d2.utils.events]:  eta: 17:12:29  iter: 298  total_loss: 1.041  loss_cls: 0.4049  loss_box_reg: 0.3394  loss_r3: 0.08615  loss_r4: 0.07789  loss_r5: 0.1186     lr: 5.974e-05  max_mem: 54479M
[11/17 01:23:20 d2.utils.events]:  eta: 16:15:34  iter: 318  total_loss: 1.033  loss_cls: 0.4098  loss_box_reg: 0.3464  loss_r3: 0.08611  loss_r4: 0.07759  loss_r5: 0.1134     lr: 6.3736e-05  max_mem: 54479M
[11/17 01:23:38 d2.utils.events]:  eta: 17:14:48  iter: 338  total_loss: 0.9725  loss_cls: 0.3389  loss_box_reg: 0.3314  loss_r3: 0.08601  loss_r4: 0.07691  loss_r5: 0.1113     lr: 6.7732e-05  max_mem: 54479M
[11/17 01:23:55 d2.utils.events]:  eta: 16:29:50  iter: 358  total_loss: 0.9303  loss_cls: 0.3515  loss_box_reg: 0.345  loss_r3: 0.08596  loss_r4: 0.07584  loss_r5: 0.1085     lr: 7.1728e-05  max_mem: 54479M
[11/17 01:24:13 d2.utils.events]:  eta: 17:21:27  iter: 378  total_loss: 0.9648  loss_cls: 0.3381  loss_box_reg: 0.3592  loss_r3: 0.08589  loss_r4: 0.07524  loss_r5: 0.1006     lr: 7.5724e-05  max_mem: 54479M
[11/17 01:24:31 d2.utils.events]:  eta: 17:18:07  iter: 398  total_loss: 0.8874  loss_cls: 0.3031  loss_box_reg: 0.3192  loss_r3: 0.08579  loss_r4: 0.07679  loss_r5: 0.1049     lr: 7.972e-05  max_mem: 54479M
[11/17 01:24:50 d2.utils.events]:  eta: 18:17:55  iter: 418  total_loss: 0.8716  loss_cls: 0.2722  loss_box_reg: 0.3271  loss_r3: 0.08572  loss_r4: 0.07533  loss_r5: 0.09554     lr: 8.3716e-05  max_mem: 54479M
[11/17 01:25:07 d2.utils.events]:  eta: 17:23:50  iter: 438  total_loss: 0.8297  loss_cls: 0.2672  loss_box_reg: 0.3065  loss_r3: 0.0856  loss_r4: 0.07476  loss_r5: 0.1007     lr: 8.7712e-05  max_mem: 54479M
[11/17 01:25:25 d2.utils.events]:  eta: 16:56:23  iter: 458  total_loss: 0.8479  loss_cls: 0.2839  loss_box_reg: 0.313  loss_r3: 0.0855  loss_r4: 0.07485  loss_r5: 0.09077     lr: 9.1708e-05  max_mem: 54479M
[11/17 01:25:44 d2.utils.events]:  eta: 18:27:02  iter: 478  total_loss: 0.8611  loss_cls: 0.2902  loss_box_reg: 0.3186  loss_r3: 0.08544  loss_r4: 0.0749  loss_r5: 0.1046     lr: 9.5704e-05  max_mem: 54479M
[11/17 01:26:08 d2.utils.events]:  eta: 23:28:38  iter: 498  total_loss: 0.8189  loss_cls: 0.2462  loss_box_reg: 0.3012  loss_r3: 0.08532  loss_r4: 0.07412  loss_r5: 0.09109     lr: 9.97e-05  max_mem: 72603M
[11/17 01:26:33 d2.utils.events]:  eta: 23:45:37  iter: 518  total_loss: 0.828  loss_cls: 0.2332  loss_box_reg: 0.3283  loss_r3: 0.08515  loss_r4: 0.07409  loss_r5: 0.11     lr: 0.0001037  max_mem: 73461M
[11/17 01:26:50 d2.utils.events]:  eta: 17:17:39  iter: 538  total_loss: 0.873  loss_cls: 0.263  loss_box_reg: 0.3446  loss_r3: 0.08511  loss_r4: 0.07407  loss_r5: 0.09578     lr: 0.00010769  max_mem: 73461M
Traceback (most recent call last):
  File "uda_train.py", line 135, in <module>
    do_train(cfg_source,cfg_target,model)
  File "uda_train.py", line 81, in do_train
    loss_dict = model(data_source, False, alpha3, alpha4, alpha5)
  File "/root/miniconda3/envs/powerbev/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/detectron2/detectron2/modeling/meta_arch/dense_detector.py", line 233, in forward
    predictions = self.head(features)
  File "/root/miniconda3/envs/powerbev/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/detectron2/detectron2/modeling/meta_arch/retinanet.py", line 438, in forward
    bbox_reg.append(self.bbox_pred(self.bbox_subnet(feature)))
  File "/root/miniconda3/envs/powerbev/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/powerbev/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/root/miniconda3/envs/powerbev/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/powerbev/lib/python3.8/site-packages/torch/nn/modules/activation.py", line 98, in forward
    return F.relu(input, inplace=self.inplace)
  File "/root/miniconda3/envs/powerbev/lib/python3.8/site-packages/torch/nn/functional.py", line 1299, in relu
    result = torch.relu(input)
RuntimeError: CUDA out of memory. Tried to allocate 1.12 GiB (GPU 0; 79.15 GiB total capacity; 74.99 GiB already allocated; 409.69 MiB free; 76.85 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

**Comment by GiovanniPasq** [comment]
Hello,
which pytorch version are you using? can you please try to add inside the do_train function and after these lines:
```
optimizer.zero_grad()
losses.backward()
optimizer.step()
storage.put_scalar("lr", optimizer.param_groups[0]["lr"], smoothing_hint=False)
scheduler.step()
```
 the following line?
```
del losses, loss_dict, loss_dict_target
```

The final snippet code is:
```
optimizer.zero_grad()
losses.backward()
optimizer.step()
storage.put_scalar("lr", optimizer.param_groups[0]["lr"], smoothing_hint=False)
scheduler.step()
del losses, loss_dict, loss_dict_target
```

**Comment by Shichang-Fu** [comment]
Thank you very much for your reply. I was using the pytorch version 1.10.0+cu111, and tried detectron2 with versions 0.2.1 and 0.6.0. But none of them worked. 
Thank you for your suggestion. I will give it a try and get back to you.

**Comment by Shichang-Fu** [comment]
I followed your advice，add the code `del losses, loss_dict, loss_dict_target`，But the same problem still arises

**Comment by GiovanniPasq** [comment]
Did you make any changes in the uda_train.py script, particularly inside the do_train() function? If you made any changes, could you please paste the updated function here? I never encountered this error while developing this code

**Comment by Shichang-Fu** [comment]
This is my code, and I've barely changed your code.
I only changed data_len,max_epoch, and cfg_source.SOLVER.MAX_ITER = 63342

`import logging
import os
import torch
import detectron2
import numpy as np
from detectron2 import model_zoo
from detectron2.engine.defaults import default_argument_parser
from detectron2.utils.logger import setup_logger
setup_logger()
import detectron2.utils.comm as comm
from detectron2.checkpoint import DetectionCheckpointer, PeriodicCheckpointer
from detectron2.config import get_cfg
from detectron2.data import (build_detection_test_loader,build_detection_train_loader,)
from detectron2.engine import default_writers
from detectron2.evaluation import (COCOEvaluator,inference_on_dataset)
from detectron2.modeling import build_model
from detectron2.solver import build_lr_scheduler, build_optimizer
from detectron2.utils.events import EventStorage
from detectron2.data.datasets import register_coco_instances
from detectron2.data.datasets import register_visdrone
from detectron2.data.datasets import register_customeperson
from detectron2.engine import launch
#training set
register_customeperson('person_trainS', '/media/ubuntu/Data/fsc/datasets/person')
register_visdrone('person_train', '/media/ubuntu/Data/fsc/datasets/visdrone-person/train')
#test set
register_visdrone('person_val', '/media/ubuntu/Data/fsc/datasets/visdrone-person/val')

logger = logging.getLogger("detectron2")

def do_train(cfg_source, cfg_target, model, resume=False):
    print(model)
    model.train()
    optimizer = build_optimizer(cfg_source, model)
    scheduler = build_lr_scheduler(cfg_source, optimizer)
    checkpointer = DetectionCheckpointer(model, cfg_source.OUTPUT_DIR, optimizer=optimizer, scheduler=scheduler)

    start_iter = (checkpointer.resume_or_load(cfg_source.MODEL.WEIGHTS, resume=resume).get("iteration", -1) + 1)
    max_iter = cfg_source.SOLVER.MAX_ITER

    periodic_checkpointer = PeriodicCheckpointer(checkpointer, cfg_source.SOLVER.CHECKPOINT_PERIOD, max_iter=max_iter)
    writers = default_writers(cfg_source.OUTPUT_DIR, max_iter) if comm.is_main_process() else []

    i = 1
    max_epoch = 18 # max iter / min(data_len(data_source, data_target)) 62000/3519
    current_epoch = 0
    data_len = 3519

    alpha3 = 0
    alpha4 = 0
    alpha5 = 0
  
    data_loader_source = build_detection_train_loader(cfg_source)
    data_loader_target = build_detection_train_loader(cfg_target) 
    logger.info("Starting training from iteration {}".format(start_iter))
    with EventStorage(start_iter) as storage:
        for data_source,data_target, iteration in zip(data_loader_source, data_loader_target, range(start_iter, max_iter)):
            storage.iter = iteration

            iteration = iteration + 1
            if (iteration % data_len) == 0:
                current_epoch += 1
                i = 1

            p = float( i + current_epoch * data_len) / max_epoch / data_len
            alpha = 2. / ( 1. + np.exp( -10 * p)) - 1
            i += 1

            alpha3 = alpha
            alpha4 = alpha
            alpha5 = alpha

            if alpha3 > 0.5:
                alpha3 = 0.5

            if alpha4 > 0.5:
                alpha4 = 0.5

            if alpha5 > 0.1:
                alpha5 = 0.1

            loss_dict = model(data_source, False, alpha3, alpha4, alpha5)
            loss_dict_target = model(data_target, True, alpha3, alpha4, alpha5)
            loss_dict["loss_r3"] += loss_dict_target["loss_r3"]
            loss_dict["loss_r4"] += loss_dict_target["loss_r4"]
            loss_dict["loss_r5"] += loss_dict_target["loss_r5"]

            loss_dict["loss_r3"] *= 0.5
            loss_dict["loss_r4"] *= 0.5
            loss_dict["loss_r5"] *= 0.5
            losses = sum(loss_dict.values())
            assert torch.isfinite(losses).all(), loss_dict

            loss_dict_reduced = {k: v.item() for k, v in comm.reduce_dict(loss_dict).items()}
            losses_reduced = sum(loss for loss in loss_dict_reduced.values())
            if comm.is_main_process():
                storage.put_scalars(total_loss=losses_reduced, **loss_dict_reduced)

            optimizer.zero_grad()
            losses.backward()
            optimizer.step()
            storage.put_scalar("lr", optimizer.param_groups[0]["lr"], smoothing_hint=False)
            scheduler.step()
            del losses, loss_dict, loss_dict_target

            if iteration - start_iter > 5 and ((iteration + 1) % 20 == 0 or iteration == max_iter - 1):
                for writer in writers:
                    writer.write()
            periodic_checkpointer.step(iteration)


    

cfg_source = get_cfg()
cfg_source.merge_from_file(model_zoo.get_config_file("COCO-Detection/retinanet_R_50_FPN_3x.yaml"))
cfg_source.DATASETS.TRAIN = ("person_trainS",)
cfg_source.DATALOADER.NUM_WORKERS = 2
cfg_source.MODEL.WEIGHTS = model_zoo.get_checkpoint_url("COCO-Detection/retinanet_R_50_FPN_3x.yaml")
cfg_source.SOLVER.IMS_PER_BATCH = 2
cfg_source.SOLVER.BASE_LR = 0.0002
cfg_source.SOLVER.WEIGHT_DECAY = 0.001
cfg_source.SOLVER.MAX_ITER = 63342
cfg_source.SOLVER.STEPS = (30000,)
cfg_source.INPUT.MIN_SIZE_TRAIN = (0,)
cfg_source.INPUT.MIN_SIZE_TEST = 0
os.makedirs(cfg_source.OUTPUT_DIR, exist_ok=True)
cfg_source.MODEL.RETINANET.NUM_CLASSES = 1
model = build_model(cfg_source)

cfg_target = get_cfg()
cfg_target.DATASETS.TRAIN = ("person_train",)
cfg_target.INPUT.MIN_SIZE_TRAIN = (0,)
cfg_target.DATALOADER.NUM_WORKERS = 2
cfg_target.SOLVER.IMS_PER_BATCH = 2

do_train(cfg_source,cfg_target,model)

#test
from detectron2.evaluation import COCOEvaluator, inference_on_dataset
evaluator = COCOEvaluator("person_val", cfg_source, False, output_dir="./output/")
val_loader = build_detection_test_loader(cfg_source, "person_val")
inference_on_dataset(model, val_loader, evaluator)`

**Comment by GiovanniPasq** [comment]
ok this is very strange, let me do some checks and as soon as I figure out what the problem is I will let you know

**Comment by GiovanniPasq** [comment]
Can you paste here how you implemented register_visdrone and register_customeperson? Do they just wrap the register_coco_instances function?

**Comment by Shichang-Fu** [comment]
This is the code I registered with my dataset, and I've never had a problem running other networks in the detectron2 framework


`import contextlib
import io
import os
import random
import cv2
import numpy as np
import json
from detectron2.structures import BoxMode
from detectron2.data import DatasetCatalog, MetadataCatalog
from detectron2.utils.file_io import PathManager
from detectron2.utils.visualizer import Visualizer
import logging
from fvcore.common.timer import Timer


logger = logging.getLogger(__name__)
thing_classes = None
id_map = None

def load_visdrone_instances(dataset_name, data_dir, extra_annotation_keys=None):
    split = dataset_name.split("_")[-1]
    json_file = os.path.join(data_dir, "%s.json" % split)
    image_path = os.path.join(data_dir, "images")
    from pycocotools.coco import COCO

    timer = Timer()
    json_file = PathManager.get_local_path(json_file)
    with contextlib.redirect_stdout(io.StringIO()):
         coco_api = COCO(json_file)
    if timer.seconds() > 1:
        logger.info("Loading {} takes {:.2f} seconds.".format(json_file, timer.seconds()))

    if dataset_name is not None:
        meta = MetadataCatalog.get(dataset_name)
        cat_ids = sorted(coco_api.getCatIds())
        cats = coco_api.loadCats(cat_ids)
        # The categories in a custom json file may not be sorted.
        thing_classes = [c["name"] for c in sorted(cats, key=lambda x: x["id"])]
        meta.set(thing_classes=thing_classes)
        if not (min(cat_ids) == 1 and max(cat_ids) == len(cat_ids)):
            if "coco" not in dataset_name:
                logger.warning("""
                    Category ids in annotations are not in [1, #categories]! We'll apply a mapping for you.
                    """
                )
        id_map = {v: i for i, v in enumerate(cat_ids)}
        meta.set(thing_dataset_id_to_contiguous_id=id_map)
        
    # sort indices for reproducible results
    img_ids = sorted(coco_api.imgs.keys())
    imgs = coco_api.loadImgs(img_ids)
    anns = [coco_api.imgToAnns[img_id] for img_id in img_ids]
    total_num_valid_anns = sum([len(x) for x in anns])
    total_num_anns = len(coco_api.anns)
    if total_num_valid_anns < total_num_anns:
        logger.warning(
            f"{json_file} contains {total_num_anns} annotations, but only "
            f"{total_num_valid_anns} of them match to images in the file."
        )

    imgs_anns = list(zip(imgs, anns))
    logger.info("Loaded {} images in COCO format from {}".format(len(imgs_anns), json_file))

    dataset_dicts = []
    ann_keys = ["iscrowd", "bbox", "category_id"] + (extra_annotation_keys or [])
    file_names = []
    for (img_dict, anno_dict_list) in imgs_anns:
        record = {}
        record["file_name"] = os.path.join(image_path, img_dict["file_name"])
        file_names.append(img_dict["file_name"])
        record["height"] = img_dict["height"]
        record["width"] = img_dict["width"]
        image_id = record["image_id"] = img_dict["id"]
        record["full_image"] = True
        record["two_stage_crop"] = False
        record["crop_area"] = np.array([-1, -1, -1, -1], dtype=np.float32)

        objs = []
        for anno in anno_dict_list:
            assert anno["image_id"] == image_id
            assert anno.get("ignore", 0) == 0, '"ignore" in COCO json file is not supported.'

            obj = {key: anno[key] for key in ann_keys if key in anno}
            if obj["category_id"] in (0, 11):
                continue
            if "bbox" in obj and len(obj["bbox"]) == 0:
                raise ValueError(
                    f"One annotation of image {image_id} contains empty 'bbox' value! "
                    "This json does not have valid COCO format."
                )
            obj['bbox'] = BoxMode.convert(obj['bbox'], BoxMode.XYWH_ABS, BoxMode.XYXY_ABS)    
            obj["bbox_mode"] = BoxMode.XYXY_ABS
            if id_map:
                annotation_category_id = obj["category_id"]
                try:
                    obj["category_id"] = id_map[annotation_category_id]
                except KeyError as e:
                    raise KeyError(
                        f"Encountered category_id={annotation_category_id} "
                        "but this id does not exist in 'categories' of the json file."
                    ) from e
            objs.append(obj)
        record["annotations"] = objs
        dataset_dicts.append(record)
    return dataset_dicts


def register_visdrone(dataset_name, data_dir):
    from pycocotools.coco import COCO
    metadata = {}

    # 1. register a function which returns dicts
    DatasetCatalog.register(dataset_name, lambda: load_visdrone_instances(dataset_name, data_dir))

    # 2. Optionally, add metadata about this dataset,
    # since they might be useful in evaluation, visualization or logging
    split = dataset_name.split("_")[-1]
    json_file = os.path.join(data_dir, "%s.json" % split)
    image_root = os.path.join(data_dir, "images")
    coco_api = COCO(json_file)
    cat_ids = sorted(coco_api.getCatIds())
    cats = coco_api.loadCats(cat_ids)
    # The categories in a custom json file may not be sorted.
    thing_classes = [c["name"] for c in sorted(cats, key=lambda x: x["id"])]
    id_map = {v: i for i, v in enumerate(cat_ids)}
    MetadataCatalog.get(dataset_name).set(
        json_file=json_file, image_root=image_root, evaluator_type="coco",
        thing_classes=thing_classes,
        thing_dataset_id_to_contiguous_id=id_map, **metadata
    )

if __name__ == "__main__":
    # 注册VisDrone数据集
    register_visdrone('person_train', '/media/ubuntu/Data/fsc/datasets/visdrone-person/train')
    register_visdrone('person_val', '/media/ubuntu/Data/fsc/datasets/visdrone-person/val')

    # 验证数据集是否被正确注册
    dataset_dicts = DatasetCatalog.get('person_train')
    sampled_data = random.choice(dataset_dicts)

    # Load the image
    img = cv2.imread(sampled_data["file_name"])

    # Create a visualizer and draw the annotations on the image
    visualizer = Visualizer(img[:, :, ::-1], metadata=MetadataCatalog.get('person_train'), scale=0.5)
    out = visualizer.draw_dataset_dict(sampled_data)

    # Display the image with annotations
    cv2.imwrite("test.jpg", out.get_image()[:, :, ::-1])
`

**Comment by GiovanniPasq** [comment]
For some unknown reason the problem could be related to these lines:

```
cfg_source.INPUT.MIN_SIZE_TRAIN = (0,)
cfg_target.INPUT.MIN_SIZE_TRAIN = (0,)
```
Please try to remove them and let me know. I had now the same problem with these lines but removing them i did not encounter it anymore. Unfortunately detectron2 is always under development and sometimes they change something in the framework which can create some problems with this repo. 

Let me know if this fix your problem.

NB: to achieve better performance you should use the FPN_101 backbone and you should try to fix the resize of the images during the training to 1333.

```
cfg_source.INPUT.MIN_SIZE_TRAIN = (1333,)
cfg_target.INPUT.MIN_SIZE_TRAIN = (1333,)
```

**Comment by Shichang-Fu** [comment]
Thanks for your guidance, I have successfully run on 3090

**Comment by GiovanniPasq** [comment]
I am happy to read this message :)

**Comment by LLLshadow** [comment]
> Thanks for your guidance, I have successfully run on 3090

hi,is the result good with your dataset?
